/**
 * Exhibit 1 — One lattice, many bases (draggable), with CVP as rounding.
 * Built on Examples 2.7/2.8 and 2.24 of the notes. All classifications on
 * screen come from exact integer arithmetic (vec2) and brute-force ground
 * truth (svp), never from assumptions.
 */
import { h, intInput, badge } from './dom'
import { LatticeView } from './latticeView'
import { sameLattice, babaiRound, det, sub, normSq, type Basis2, type Vec2 } from '../lattice/vec2'
import { closestVector } from '../lattice/svp'

interface Preset {
  name: string
  lattice: Basis2
  basis: Basis2
  t: Vec2
  note: string
}

const PRESETS: Preset[] = [
  {
    name: 'Good basis B (Ex 2.24)',
    lattice: [
      [5, 3],
      [2, 7],
    ],
    basis: [
      [5, 3],
      [2, 7],
    ],
    t: [5, 6],
    note: 'short, nearly orthogonal vectors — rounding decodes well',
  },
  {
    name: 'Bad basis B′ (Ex 2.24)',
    lattice: [
      [5, 3],
      [2, 7],
    ],
    basis: [
      [12, 13],
      [7, 10],
    ],
    t: [5, 6],
    note: 'long, nearly parallel vectors — same lattice, rounding decodes badly',
  },
  {
    name: 'Good basis B₂ (Ex 2.7)',
    lattice: [
      [2, 0],
      [0, 1],
    ],
    basis: [
      [2, 0],
      [0, 1],
    ],
    t: [5, 6],
    note: 'the rectangular lattice L₂ with its orthogonal basis',
  },
  {
    name: 'Bad basis B₃ (Ex 2.8)',
    lattice: [
      [2, 0],
      [0, 1],
    ],
    basis: [
      [-2, -2],
      [4, 3],
    ],
    t: [5, 6],
    note: 'the same L₂ generated by two skewed vectors',
  },
]

export function mountExhibitLattice(root: HTMLElement): void {
  let lattice: Basis2 = PRESETS[0].lattice
  let basis: Basis2 = PRESETS[0].basis
  let t: Vec2 = PRESETS[0].t

  const view = new LatticeView(
    {
      extent: 14,
      sizePx: 520,
      onDrag: (what, p) => {
        if (what === 't') t = p
        else if (what === 'b1') basis = [p, basis[1]]
        else basis = [basis[0], p]
        syncInputs()
        update()
      },
    },
    'Interactive 2D lattice',
  )

  const status = h('p', { class: 'panel-status', role: 'status' })
  const cvpStatus = h('p', { class: 'panel-status', role: 'status' })

  const inputs: HTMLInputElement[] = []
  const fields = h('div', { class: 'field-row' })
  const defs: [string, string, () => number, (v: number) => void][] = [
    ['ex1-b1x', 'b₁ x', () => basis[0][0], (v) => (basis = [[v, basis[0][1]], basis[1]])],
    ['ex1-b1y', 'b₁ y', () => basis[0][1], (v) => (basis = [[basis[0][0], v], basis[1]])],
    ['ex1-b2x', 'b₂ x', () => basis[1][0], (v) => (basis = [basis[0], [v, basis[1][1]]])],
    ['ex1-b2y', 'b₂ y', () => basis[1][1], (v) => (basis = [basis[0], [basis[1][0], v]])],
    ['ex1-tx', 'target x', () => t[0], (v) => (t = [v, t[1]])],
    ['ex1-ty', 'target y', () => t[1], (v) => (t = [t[0], v])],
  ]
  for (const [id, label, get, set] of defs) {
    const { wrap, input } = intInput(id, label, get(), -14, 14, (v) => {
      set(v)
      update()
    })
    inputs.push(input)
    fields.append(wrap)
  }

  function syncInputs(): void {
    const vals = [basis[0][0], basis[0][1], basis[1][0], basis[1][1], t[0], t[1]]
    inputs.forEach((inp, i) => (inp.value = String(vals[i])))
  }

  const presetRow = h('div', { class: 'button-row', role: 'group', 'aria-label': 'Basis presets' })
  for (const p of PRESETS) {
    const btn = h('button', { type: 'button', text: p.name, title: p.note })
    btn.addEventListener('click', () => {
      lattice = p.lattice
      basis = p.basis
      t = p.t
      syncInputs()
      update()
    })
    presetRow.append(btn)
  }

  function update(): void {
    const d = det(basis)
    const degenerate = d === 0
    const same = !degenerate && sameLattice(lattice, basis)

    let scene
    let statusFrag: (HTMLElement | string)[]
    if (degenerate) {
      scene = { lattice, basis, parallelogram: false }
      statusFrag = [
        badge('bad', 'degenerate: b₁ and b₂ are parallel (det = 0) — they only generate a line, not a lattice'),
      ]
    } else {
      scene = { lattice, basis, parallelogram: true, overlayBasisLattice: !same }
      statusFrag = same
        ? [
            badge('ok', `same lattice — det ${d} (area ${Math.abs(d)}, matches: unimodular change of basis)`),
          ]
        : [
            badge(
              'warn',
              `different lattice — det ${d} vs ${det(lattice)}: these vectors generate the hollow points, not the original dots`,
            ),
          ]
    }

    // CVP by rounding, against whatever basis is on screen
    if (!degenerate) {
      const r = babaiRound(basis, t)
      const truth = closestVector(lattice, t)
      const errSq = normSq(sub(t, r.point))
      const [c1, c2] = r.realCoords
      const roundedHitsTruth = errSq === truth.distSq
      scene = {
        ...scene,
        target: { t, rounded: r.point, closest: truth.v },
      }
      cvpStatus.replaceChildren(
        h(
          'span',
          {},
          `t = (${t[0]}, ${t[1]}) = ${c1.toFixed(2)}·b₁ + ${c2.toFixed(2)}·b₂ → round → ${r.coeffs[0]}·b₁ + ${r.coeffs[1]}·b₂ = (${r.point[0]}, ${r.point[1]}), error √${errSq} ≈ ${Math.sqrt(errSq).toFixed(2)}. True closest point: (${truth.v[0]}, ${truth.v[1]}) at distance √${truth.distSq} ≈ ${Math.sqrt(truth.distSq).toFixed(2)} (exhaustive search). `,
        ),
        roundedHitsTruth
          ? badge('ok', 'rounding found a closest vector')
          : badge('warn', 'rounding missed the closest vector'),
      )
    } else {
      cvpStatus.replaceChildren('CVP needs two independent basis vectors.')
    }

    view.render(scene)
    status.replaceChildren(...statusFrag)
    view.setAriaLabel(
      `Lattice with basis vectors b1 (${basis[0][0]}, ${basis[0][1]}) and b2 (${basis[1][0]}, ${basis[1][1]}); ` +
        (degenerate
          ? 'degenerate basis. '
          : same
            ? 'generates the reference lattice. '
            : 'generates a different lattice than the reference. ') +
        `Target point (${t[0]}, ${t[1]}).`,
    )
  }

  const legend = h(
    'p',
    { class: 'legend' },
    h('span', { class: 'legend-item legend-b1', text: '→ b₁' }),
    h('span', { class: 'legend-item legend-b2', text: '→ b₂' }),
    h('span', { class: 'legend-item legend-target', text: '● target t' }),
    h('span', { class: 'legend-item legend-rounded', text: '● rounded decode' }),
    h('span', { class: 'legend-item legend-closest', text: '○ true closest' }),
  )

  root.append(
    presetRow,
    h('div', { class: 'lattice-layout' }, view.svg, h('div', { class: 'lattice-controls' }, fields, legend, status, cvpStatus)),
  )
  syncInputs()
  update()
}
