/**
 * Shared SVG lattice renderer. Pure view: callers pass a scene description;
 * everything is redrawn from scratch (the scenes are tiny). The SVG carries
 * role="img" with a caller-maintained aria-label; all interactive control is
 * done through the callers' buttons and numeric inputs, with optional pointer
 * dragging on the SVG as a mouse/touch convenience.
 */
import { s } from './dom'
import { pointsInBox, add, scale, type Basis2, type Vec2 } from '../lattice/vec2'

export interface LatticeScene {
  /** fixed reference lattice to draw as dots */
  lattice: Basis2
  /** current basis arrows */
  basis?: Basis2
  /** shade the fundamental parallelogram of `basis` */
  parallelogram?: boolean
  /** overlay hollow markers for the lattice generated by `basis` (when ≠ reference) */
  overlayBasisLattice?: boolean
  /** highlighted vectors from the origin, e.g. the shortest vector */
  highlight?: { v: Vec2; label: string }[]
  /** CVP: target point, its Babai-rounded lattice point, and the true closest */
  target?: { t: Vec2; rounded: Vec2; closest: Vec2 }
}

export interface LatticeViewOptions {
  /** world half-extent: view covers [-extent, extent]² */
  extent: number
  sizePx: number
  /** called with world coords when a draggable item moves (snapped to integers) */
  onDrag?: (what: 'b1' | 'b2' | 't', p: Vec2) => void
}

export class LatticeView {
  readonly svg: SVGSVGElement
  private opts: LatticeViewOptions
  private scene: LatticeScene | null = null
  private dragging: 'b1' | 'b2' | 't' | null = null

  constructor(opts: LatticeViewOptions, ariaLabel: string) {
    this.opts = opts
    this.svg = s('svg', {
      viewBox: `0 0 ${opts.sizePx} ${opts.sizePx}`,
      role: 'img',
      'aria-label': ariaLabel,
      class: 'lattice-svg',
    }) as SVGSVGElement
    if (opts.onDrag) {
      this.svg.addEventListener('pointerdown', (ev) => this.pointerDown(ev))
      this.svg.addEventListener('pointermove', (ev) => this.pointerMove(ev))
      this.svg.addEventListener('pointerup', () => (this.dragging = null))
      this.svg.addEventListener('pointercancel', () => (this.dragging = null))
    }
  }

  setAriaLabel(label: string): void {
    this.svg.setAttribute('aria-label', label)
  }

  private toPx(p: Vec2): [number, number] {
    const { extent, sizePx } = this.opts
    const u = sizePx / (2 * extent)
    return [(p[0] + extent) * u, (extent - p[1]) * u]
  }

  private toWorld(x: number, y: number): Vec2 {
    const { extent, sizePx } = this.opts
    const rect = this.svg.getBoundingClientRect()
    const px = ((x - rect.left) / rect.width) * sizePx
    const py = ((y - rect.top) / rect.height) * sizePx
    const u = sizePx / (2 * extent)
    return [Math.round(px / u - extent), Math.round(extent - py / u)]
  }

  private pointerDown(ev: PointerEvent): void {
    if (!this.scene) return
    const w = this.toWorld(ev.clientX, ev.clientY)
    const near = (p: Vec2 | undefined): boolean =>
      !!p && Math.abs(p[0] - w[0]) <= 1 && Math.abs(p[1] - w[1]) <= 1
    if (this.scene.target && near(this.scene.target.t)) this.dragging = 't'
    else if (this.scene.basis && near(this.scene.basis[0])) this.dragging = 'b1'
    else if (this.scene.basis && near(this.scene.basis[1])) this.dragging = 'b2'
    if (this.dragging) {
      this.svg.setPointerCapture(ev.pointerId)
      ev.preventDefault()
    }
  }

  private pointerMove(ev: PointerEvent): void {
    if (!this.dragging || !this.opts.onDrag) return
    const w = this.toWorld(ev.clientX, ev.clientY)
    const e = this.opts.extent
    const clamped: Vec2 = [Math.max(-e, Math.min(e, w[0])), Math.max(-e, Math.min(e, w[1]))]
    this.opts.onDrag(this.dragging, clamped)
  }

  render(scene: LatticeScene): void {
    this.scene = scene
    const { extent, sizePx } = this.opts
    const svg = this.svg
    svg.textContent = ''

    // unit grid + axes
    const grid = s('g', { class: 'lv-grid', 'aria-hidden': 'true' })
    for (let i = -extent; i <= extent; i++) {
      const [x1] = this.toPx([i, 0])
      const [, y1] = this.toPx([0, i])
      grid.append(
        s('line', { x1: String(x1), y1: '0', x2: String(x1), y2: String(sizePx), class: i === 0 ? 'lv-axis' : 'lv-gridline' }),
        s('line', { x1: '0', y1: String(y1), x2: String(sizePx), y2: String(y1), class: i === 0 ? 'lv-axis' : 'lv-gridline' }),
      )
    }
    svg.append(grid)

    // fundamental parallelogram
    if (scene.basis && scene.parallelogram) {
      const [b1, b2] = scene.basis
      const pts = [[0, 0] as Vec2, b1, add(b1, b2), b2].map((p) => this.toPx(p).join(',')).join(' ')
      svg.append(s('polygon', { points: pts, class: 'lv-para' }))
    }

    // reference lattice points
    const dots = s('g', { class: 'lv-dots' })
    for (const p of pointsInBox(scene.lattice, -extent, extent, -extent, extent)) {
      const [cx, cy] = this.toPx(p)
      dots.append(s('circle', { cx: String(cx), cy: String(cy), r: '3.2', class: 'lv-dot' }))
    }
    svg.append(dots)

    // overlay: lattice generated by the current (dragged) basis, when different
    if (scene.basis && scene.overlayBasisLattice) {
      const overlay = s('g', { class: 'lv-overlay' })
      for (const p of pointsInBox(scene.basis, -extent, extent, -extent, extent)) {
        const [cx, cy] = this.toPx(p)
        overlay.append(s('circle', { cx: String(cx), cy: String(cy), r: '5.4', class: 'lv-dot-overlay' }))
      }
      svg.append(overlay)
    }

    // highlighted vectors
    for (const hl of scene.highlight ?? []) {
      this.arrow(hl.v, 'lv-highlight', hl.label)
    }

    // basis arrows
    if (scene.basis) {
      this.arrow(scene.basis[0], 'lv-b1', 'b₁')
      this.arrow(scene.basis[1], 'lv-b2', 'b₂')
    }

    // CVP target / rounded / closest
    if (scene.target) {
      const { t, rounded, closest } = scene.target
      const [tx, ty] = this.toPx(t)
      const [rx, ry] = this.toPx(rounded)
      const [cx, cy] = this.toPx(closest)
      svg.append(
        s('line', { x1: String(tx), y1: String(ty), x2: String(rx), y2: String(ry), class: 'lv-error' }),
        s('circle', { cx: String(cx), cy: String(cy), r: '9', class: 'lv-closest' }),
        s('circle', { cx: String(rx), cy: String(ry), r: '5.5', class: 'lv-rounded' }),
        s('circle', { cx: String(tx), cy: String(ty), r: '5.5', class: 'lv-target' }),
      )
      const label = s('text', { x: String(tx + 9), y: String(ty - 7), class: 'lv-label lv-target-label' }, 't')
      svg.append(label)
    }
  }

  private arrow(v: Vec2, cls: string, label: string): void {
    if (v[0] === 0 && v[1] === 0) return
    const [x0, y0] = this.toPx([0, 0])
    const [x1, y1] = this.toPx(v)
    const ang = Math.atan2(y1 - y0, x1 - x0)
    const headLen = 9
    const h1x = x1 - headLen * Math.cos(ang - 0.42)
    const h1y = y1 - headLen * Math.sin(ang - 0.42)
    const h2x = x1 - headLen * Math.cos(ang + 0.42)
    const h2y = y1 - headLen * Math.sin(ang + 0.42)
    const g = s(
      'g',
      { class: `lv-arrow ${cls}` },
      s('line', { x1: String(x0), y1: String(y0), x2: String(x1), y2: String(y1) }),
      s('polygon', { points: `${x1},${y1} ${h1x},${h1y} ${h2x},${h2y}` }),
      s('circle', { cx: String(x1), cy: String(y1), r: '10', class: 'lv-handle' }),
      s('text', { x: String(x1 + 11), y: String(y1 + 4), class: 'lv-label' }, label),
    )
    this.svg.append(g)
  }
}

/** Scale a basis view so the notes' Example 9.11 vectors fit comfortably. */
export const scaleBasis = (B: Basis2, f: number): Basis2 => [scale(B[0], f), scale(B[1], f)]
